### ISSUE TITLE
Create error when you cannot find emcc

### ISSUE THREAD

**Issue by justinmann** [mezum/emcc-loader#3]
If emcc is not available on the path, the loader fails with a non-intuitive error:
ERROR in ./src/foo.clist
Module build failed: Error: ENOENT: no such file or directory, open '/Users/jusmann/aws/aws-demo/dist/foo.js'
 @ ./src/app.ts 7:36-58
 
 Here is the sample app:
 https://github.com/justinmann/aws-demo

**Comment by mezum** [comment]
I fixed it to emit user-friendly message.
Thank you for your report.
